### ISSUE TITLE
Missing some teams in the predictor data

### ISSUE THREAD

**Issue by bans1mp** [bans1mp/EPL_Prediciton#1]

**Comment by generalkakru** [comment]
What's the issue exactly

**Comment by bans1mp** [comment]
The data is missing some teams which is affecting the prediction system and i dont know how to fix it.

**Comment by generalkakru** [comment]
No no whats YOUR issue i mean

**Comment by generalkakru** [comment]
kindly check
sent pull req.

**Comment by bans1mp** [comment]
checked lgtm
